// <auto-generated />
using System;
using Dogtoralia.MVC.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Dogtoralia.MVC.Migrations
{
    [DbContext(typeof(DogtoraliaDbContext))]
    [Migration("20260320005801_AddAppointments")]
    partial class AddAppointments
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Dogtoralia.Shared.Models.Appointment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AppointmentDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ClinicId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("PetId")
                        .HasColumnType("int");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int?>("VeterinarianId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ClinicId");

                    b.HasIndex("PetId");

                    b.HasIndex("VeterinarianId");

                    b.ToTable("Appointments");
                });

            modelBuilder.Entity("Dogtoralia.Shared.Models.Clinic", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("SpecialityId")
                        .HasColumnType("int");

                    b.Property<string>("Website")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("SpecialityId");

                    b.ToTable("Clinics");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Av. Insurgentes Sur 1234, San Ángel, CDMX",
                            CreatedAt = new DateTime(2024, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Clínica de medicina general para mascotas en San Ángel.",
                            Email = "contacto@sanangelvет.mx",
                            Name = "Clínica Veterinaria San Ángel",
                            Phone = "+52-55-5550-1001",
                            SpecialityId = 1,
                            Website = "https://sanangelvет.mx"
                        },
                        new
                        {
                            Id = 2,
                            Address = "Presidente Masaryk 321, Polanco, CDMX",
                            CreatedAt = new DateTime(2024, 2, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Especialistas en dermatología veterinaria.",
                            Email = "info@dermapetpolanco.mx",
                            Name = "DermaPet Polanco",
                            Phone = "+52-55-5550-2002",
                            SpecialityId = 2,
                            Website = "https://dermapetpolanco.mx"
                        },
                        new
                        {
                            Id = 3,
                            Address = "Av. Vallarta 4560, Guadalajara, Jalisco",
                            CreatedAt = new DateTime(2024, 3, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Cirugía y rehabilitación ortopédica para animales.",
                            Email = "ortopaws@gdl.mx",
                            Name = "OrtoPaws Guadalajara",
                            Phone = "+52-33-3333-3003",
                            SpecialityId = 3
                        },
                        new
                        {
                            Id = 4,
                            Address = "Av. Garza Sada 2501, Monterrey, NL",
                            CreatedAt = new DateTime(2024, 4, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Cardiología veterinaria de alta especialidad.",
                            Email = "cardiovet@mty.mx",
                            Name = "CardioVet Monterrey",
                            Phone = "+52-81-8181-4004",
                            SpecialityId = 4,
                            Website = "https://cardiovetmty.mx"
                        },
                        new
                        {
                            Id = 5,
                            Address = "Blvd. Atlixcáyotl 2000, Puebla, PUE",
                            CreatedAt = new DateTime(2024, 5, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Centro oncológico veterinario en Puebla.",
                            Email = "oncoanimal@puebla.mx",
                            Name = "OncoAnimal Puebla",
                            Phone = "+52-22-2222-5005",
                            SpecialityId = 5
                        },
                        new
                        {
                            Id = 6,
                            Address = "Francisco Sosa 150, Coyoacán, CDMX",
                            CreatedAt = new DateTime(2024, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Atención integral y medicina preventiva para mascotas.",
                            Email = "integral@coyoacanvet.mx",
                            Name = "Clínica Integral Coyoacán",
                            Phone = "+52-55-5550-6006",
                            SpecialityId = 1,
                            Website = "https://coyoacanvet.mx"
                        });
                });

            modelBuilder.Entity("Dogtoralia.Shared.Models.Pet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Breed")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("OwnerEmail")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("OwnerName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("OwnerPhone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Species")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Pets");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Breed = "Labrador Retriever",
                            CreatedAt = new DateTime(2024, 1, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(2020, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Max",
                            Notes = "Alérgico al pollo.",
                            OwnerEmail = "jorge.sanchez@gmail.com",
                            OwnerName = "Jorge Sánchez",
                            OwnerPhone = "+52-55-1234-5601",
                            Species = "Perro"
                        },
                        new
                        {
                            Id = 2,
                            Breed = "Siamese",
                            CreatedAt = new DateTime(2024, 2, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(2021, 7, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Luna",
                            OwnerEmail = "maria.fernandez@outlook.com",
                            OwnerName = "María Fernández",
                            OwnerPhone = "+52-55-1234-5602",
                            Species = "Gato"
                        },
                        new
                        {
                            Id = 3,
                            Breed = "African Grey Parrot",
                            CreatedAt = new DateTime(2024, 2, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(2018, 11, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Paco",
                            Notes = "Habla español.",
                            OwnerEmail = "andres.gomez@yahoo.com",
                            OwnerName = "Andrés Gómez",
                            OwnerPhone = "+52-33-9876-5603",
                            Species = "Ave"
                        },
                        new
                        {
                            Id = 4,
                            Breed = "Golden Retriever",
                            CreatedAt = new DateTime(2024, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(2019, 5, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Bella",
                            OwnerEmail = "patricia.lopez@gmail.com",
                            OwnerName = "Patricia López",
                            OwnerPhone = "+52-81-5555-5604",
                            Species = "Perro"
                        },
                        new
                        {
                            Id = 5,
                            Breed = "Persian",
                            CreatedAt = new DateTime(2024, 3, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(2022, 1, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Mimi",
                            Notes = "Pelo largo, requiere grooming mensual.",
                            OwnerEmail = "roberto.diaz@hotmail.com",
                            OwnerName = "Roberto Díaz",
                            OwnerPhone = "+52-55-1234-5605",
                            Species = "Gato"
                        },
                        new
                        {
                            Id = 6,
                            Breed = "German Shepherd",
                            CreatedAt = new DateTime(2024, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(2020, 9, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Rocky",
                            OwnerEmail = "lucia.herrera@gmail.com",
                            OwnerName = "Lucía Herrera",
                            OwnerPhone = "+52-22-7777-5606",
                            Species = "Perro"
                        },
                        new
                        {
                            Id = 7,
                            Breed = "Cockatiel",
                            CreatedAt = new DateTime(2024, 4, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(2023, 2, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Coco",
                            Notes = "Muy sociable.",
                            OwnerEmail = "eduardo.torres@gmail.com",
                            OwnerName = "Eduardo Torres",
                            OwnerPhone = "+52-55-1234-5607",
                            Species = "Ave"
                        },
                        new
                        {
                            Id = 8,
                            Breed = "Maine Coon",
                            CreatedAt = new DateTime(2024, 5, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(2020, 6, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Nala",
                            OwnerEmail = "gabriela.ruiz@outlook.com",
                            OwnerName = "Gabriela Ruiz",
                            OwnerPhone = "+52-33-3333-5608",
                            Species = "Gato"
                        },
                        new
                        {
                            Id = 9,
                            Breed = "Holland Lop",
                            CreatedAt = new DateTime(2024, 5, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(2022, 10, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Tito",
                            Notes = "Dieta especial sin pellets.",
                            OwnerEmail = "felipe.morales@yahoo.com",
                            OwnerName = "Felipe Morales",
                            OwnerPhone = "+52-81-8888-5609",
                            Species = "Conejo"
                        },
                        new
                        {
                            Id = 10,
                            Breed = "Beagle",
                            CreatedAt = new DateTime(2024, 6, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(2021, 12, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Kira",
                            OwnerEmail = "isabella.castro@gmail.com",
                            OwnerName = "Isabella Castro",
                            OwnerPhone = "+52-55-1234-5610",
                            Species = "Perro"
                        });
                });

            modelBuilder.Entity("Dogtoralia.Shared.Models.Speciality", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Specialities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Medicina General"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Dermatología"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Ortopedia"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Cardiología"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Oncología"
                        });
                });

            modelBuilder.Entity("Dogtoralia.Shared.Models.Veterinarian", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClinicId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LicenseNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("YearsOfExperience")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ClinicId");

                    b.HasIndex("LicenseNumber")
                        .IsUnique();

                    b.ToTable("Veterinarians");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ClinicId = 1,
                            Email = "c.mendoza@sanangelvет.mx",
                            FirstName = "Carlos",
                            LastName = "Mendoza Ruiz",
                            LicenseNumber = "MV-100001",
                            Phone = "+52-55-5550-1101",
                            YearsOfExperience = 10
                        },
                        new
                        {
                            Id = 2,
                            ClinicId = 1,
                            Email = "l.garcia@sanangelvет.mx",
                            FirstName = "Laura",
                            LastName = "García Pérez",
                            LicenseNumber = "MV-100002",
                            Phone = "+52-55-5550-1102",
                            YearsOfExperience = 7
                        },
                        new
                        {
                            Id = 3,
                            ClinicId = 2,
                            Email = "m.torres@dermapetpolanco.mx",
                            FirstName = "Miguel",
                            LastName = "Torres Sánchez",
                            LicenseNumber = "MV-100003",
                            Phone = "+52-55-5550-2101",
                            YearsOfExperience = 12
                        },
                        new
                        {
                            Id = 4,
                            ClinicId = 2,
                            Email = "a.lopez@dermapetpolanco.mx",
                            FirstName = "Ana",
                            LastName = "López Hernández",
                            LicenseNumber = "MV-100004",
                            Phone = "+52-55-5550-2102",
                            YearsOfExperience = 5
                        },
                        new
                        {
                            Id = 5,
                            ClinicId = 3,
                            Email = "r.castillo@gdl.mx",
                            FirstName = "Roberto",
                            LastName = "Castillo Vega",
                            LicenseNumber = "MV-100005",
                            Phone = "+52-33-3333-3101",
                            YearsOfExperience = 15
                        },
                        new
                        {
                            Id = 6,
                            ClinicId = 3,
                            Email = "s.ramirez@gdl.mx",
                            FirstName = "Sofia",
                            LastName = "Ramírez Díaz",
                            LicenseNumber = "MV-100006",
                            Phone = "+52-33-3333-3102",
                            YearsOfExperience = 8
                        },
                        new
                        {
                            Id = 7,
                            ClinicId = 4,
                            Email = "d.morales@mty.mx",
                            FirstName = "Diego",
                            LastName = "Morales Cruz",
                            LicenseNumber = "MV-100007",
                            Phone = "+52-81-8181-4101",
                            YearsOfExperience = 20
                        },
                        new
                        {
                            Id = 8,
                            ClinicId = 4,
                            Email = "v.jimenez@mty.mx",
                            FirstName = "Valeria",
                            LastName = "Jiménez Flores",
                            LicenseNumber = "MV-100008",
                            Phone = "+52-81-8181-4102",
                            YearsOfExperience = 6
                        },
                        new
                        {
                            Id = 9,
                            ClinicId = 5,
                            Email = "h.reyes@puebla.mx",
                            FirstName = "Héctor",
                            LastName = "Reyes Martínez",
                            LicenseNumber = "MV-100009",
                            Phone = "+52-22-2222-5101",
                            YearsOfExperience = 18
                        },
                        new
                        {
                            Id = 10,
                            ClinicId = 6,
                            Email = "c.navarro@coyoacanvet.mx",
                            FirstName = "Carmen",
                            LastName = "Navarro Ortiz",
                            LicenseNumber = "MV-100010",
                            Phone = "+52-55-5550-6101",
                            YearsOfExperience = 9
                        });
                });

            modelBuilder.Entity("Dogtoralia.Shared.Models.Appointment", b =>
                {
                    b.HasOne("Dogtoralia.Shared.Models.Clinic", "Clinic")
                        .WithMany("Appointments")
                        .HasForeignKey("ClinicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Dogtoralia.Shared.Models.Pet", "Pet")
                        .WithMany("Appointments")
                        .HasForeignKey("PetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Dogtoralia.Shared.Models.Veterinarian", "Veterinarian")
                        .WithMany("Appointments")
                        .HasForeignKey("VeterinarianId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Clinic");

                    b.Navigation("Pet");

                    b.Navigation("Veterinarian");
                });

            modelBuilder.Entity("Dogtoralia.Shared.Models.Clinic", b =>
                {
                    b.HasOne("Dogtoralia.Shared.Models.Speciality", "Speciality")
                        .WithMany("Clinics")
                        .HasForeignKey("SpecialityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Speciality");
                });

            modelBuilder.Entity("Dogtoralia.Shared.Models.Veterinarian", b =>
                {
                    b.HasOne("Dogtoralia.Shared.Models.Clinic", "Clinic")
                        .WithMany("Veterinarians")
                        .HasForeignKey("ClinicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Clinic");
                });

            modelBuilder.Entity("Dogtoralia.Shared.Models.Clinic", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("Veterinarians");
                });

            modelBuilder.Entity("Dogtoralia.Shared.Models.Pet", b =>
                {
                    b.Navigation("Appointments");
                });

            modelBuilder.Entity("Dogtoralia.Shared.Models.Speciality", b =>
                {
                    b.Navigation("Clinics");
                });

            modelBuilder.Entity("Dogtoralia.Shared.Models.Veterinarian", b =>
                {
                    b.Navigation("Appointments");
                });
#pragma warning restore 612, 618
        }
    }
}
