// <auto-generated />
using System;
using Dogtoralia.MVC.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Dogtoralia.MVC.Migrations
{
    [DbContext(typeof(DogtoraliaDbContext))]
    [Migration("20260417233631_AddIdentity")]
    partial class AddIdentity
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Dogtoralia.Shared.Models.Appointment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AppointmentDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ClinicId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("PetId")
                        .HasColumnType("int");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int?>("VeterinarianId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ClinicId");

                    b.HasIndex("PetId");

                    b.HasIndex("VeterinarianId");

                    b.ToTable("Appointments");
                });

            modelBuilder.Entity("Dogtoralia.Shared.Models.Clinic", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("SpecialityId")
                        .HasColumnType("int");

                    b.Property<string>("Website")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("SpecialityId");

                    b.ToTable("Clinics");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Av. Insurgentes Sur 1234, San Ángel, CDMX",
                            CreatedAt = new DateTime(2024, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Clínica de medicina general para mascotas en San Ángel.",
                            Email = "contacto@sanangelvет.mx",
                            Name = "Clínica Veterinaria San Ángel",
                            Phone = "+52-55-5550-1001",
                            SpecialityId = 1,
                            Website = "https://sanangelvет.mx"
                        },
                        new
                        {
                            Id = 2,
                            Address = "Presidente Masaryk 321, Polanco, CDMX",
                            CreatedAt = new DateTime(2024, 2, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Especialistas en dermatología veterinaria.",
                            Email = "info@dermapetpolanco.mx",
                            Name = "DermaPet Polanco",
                            Phone = "+52-55-5550-2002",
                            SpecialityId = 2,
                            Website = "https://dermapetpolanco.mx"
                        },
                        new
                        {
                            Id = 3,
                            Address = "Av. Vallarta 4560, Guadalajara, Jalisco",
                            CreatedAt = new DateTime(2024, 3, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Cirugía y rehabilitación ortopédica para animales.",
                            Email = "ortopaws@gdl.mx",
                            Name = "OrtoPaws Guadalajara",
                            Phone = "+52-33-3333-3003",
                            SpecialityId = 3
                        },
                        new
                        {
                            Id = 4,
                            Address = "Av. Garza Sada 2501, Monterrey, NL",
                            CreatedAt = new DateTime(2024, 4, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Cardiología veterinaria de alta especialidad.",
                            Email = "cardiovet@mty.mx",
                            Name = "CardioVet Monterrey",
                            Phone = "+52-81-8181-4004",
                            SpecialityId = 4,
                            Website = "https://cardiovetmty.mx"
                        },
                        new
                        {
                            Id = 5,
                            Address = "Blvd. Atlixcáyotl 2000, Puebla, PUE",
                            CreatedAt = new DateTime(2024, 5, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Centro oncológico veterinario en Puebla.",
                            Email = "oncoanimal@puebla.mx",
                            Name = "OncoAnimal Puebla",
                            Phone = "+52-22-2222-5005",
                            SpecialityId = 5
                        },
                        new
                        {
                            Id = 6,
                            Address = "Francisco Sosa 150, Coyoacán, CDMX",
                            CreatedAt = new DateTime(2024, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Atención integral y medicina preventiva para mascotas.",
                            Email = "integral@coyoacanvet.mx",
                            Name = "Clínica Integral Coyoacán",
                            Phone = "+52-55-5550-6006",
                            SpecialityId = 1,
                            Website = "https://coyoacanvet.mx"
                        });
                });

            modelBuilder.Entity("Dogtoralia.Shared.Models.Pet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Breed")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("PetOwnerId")
                        .HasColumnType("int");

                    b.Property<string>("Species")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("PetOwnerId");

                    b.ToTable("Pets");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Breed = "Labrador Retriever",
                            CreatedAt = new DateTime(2024, 1, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(2020, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Max",
                            Notes = "Alérgico al pollo.",
                            PetOwnerId = 1,
                            Species = "Perro"
                        },
                        new
                        {
                            Id = 2,
                            Breed = "Siamese",
                            CreatedAt = new DateTime(2024, 2, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(2021, 7, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Luna",
                            PetOwnerId = 2,
                            Species = "Gato"
                        },
                        new
                        {
                            Id = 3,
                            Breed = "African Grey Parrot",
                            CreatedAt = new DateTime(2024, 2, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(2018, 11, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Paco",
                            Notes = "Habla español.",
                            PetOwnerId = 3,
                            Species = "Ave"
                        },
                        new
                        {
                            Id = 4,
                            Breed = "Golden Retriever",
                            CreatedAt = new DateTime(2024, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(2019, 5, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Bella",
                            PetOwnerId = 4,
                            Species = "Perro"
                        },
                        new
                        {
                            Id = 5,
                            Breed = "Persian",
                            CreatedAt = new DateTime(2024, 3, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(2022, 1, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Mimi",
                            Notes = "Pelo largo, requiere grooming mensual.",
                            PetOwnerId = 5,
                            Species = "Gato"
                        },
                        new
                        {
                            Id = 6,
                            Breed = "German Shepherd",
                            CreatedAt = new DateTime(2024, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(2020, 9, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Rocky",
                            PetOwnerId = 6,
                            Species = "Perro"
                        },
                        new
                        {
                            Id = 7,
                            Breed = "Cockatiel",
                            CreatedAt = new DateTime(2024, 4, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(2023, 2, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Coco",
                            Notes = "Muy sociable.",
                            PetOwnerId = 7,
                            Species = "Ave"
                        },
                        new
                        {
                            Id = 8,
                            Breed = "Maine Coon",
                            CreatedAt = new DateTime(2024, 5, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(2020, 6, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Nala",
                            PetOwnerId = 8,
                            Species = "Gato"
                        },
                        new
                        {
                            Id = 9,
                            Breed = "Holland Lop",
                            CreatedAt = new DateTime(2024, 5, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(2022, 10, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Tito",
                            Notes = "Dieta especial sin pellets.",
                            PetOwnerId = 9,
                            Species = "Conejo"
                        },
                        new
                        {
                            Id = 10,
                            Breed = "Beagle",
                            CreatedAt = new DateTime(2024, 6, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(2021, 12, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Kira",
                            PetOwnerId = 10,
                            Species = "Perro"
                        });
                });

            modelBuilder.Entity("Dogtoralia.Shared.Models.PetOwner", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasFilter("[UserId] IS NOT NULL");

                    b.ToTable("PetOwners");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2024, 1, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "jorge.sanchez@gmail.com",
                            Name = "Jorge Sánchez",
                            Phone = "+52-55-1234-5601"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2024, 2, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "maria.fernandez@outlook.com",
                            Name = "María Fernández",
                            Phone = "+52-55-1234-5602"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2024, 2, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "andres.gomez@yahoo.com",
                            Name = "Andrés Gómez",
                            Phone = "+52-33-9876-5603"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2024, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "patricia.lopez@gmail.com",
                            Name = "Patricia López",
                            Phone = "+52-81-5555-5604"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2024, 3, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "roberto.diaz@hotmail.com",
                            Name = "Roberto Díaz",
                            Phone = "+52-55-1234-5605"
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2024, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "lucia.herrera@gmail.com",
                            Name = "Lucía Herrera",
                            Phone = "+52-22-7777-5606"
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2024, 4, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "eduardo.torres@gmail.com",
                            Name = "Eduardo Torres",
                            Phone = "+52-55-1234-5607"
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2024, 5, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "gabriela.ruiz@outlook.com",
                            Name = "Gabriela Ruiz",
                            Phone = "+52-33-3333-5608"
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2024, 5, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "felipe.morales@yahoo.com",
                            Name = "Felipe Morales",
                            Phone = "+52-81-8888-5609"
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2024, 6, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "isabella.castro@gmail.com",
                            Name = "Isabella Castro",
                            Phone = "+52-55-1234-5610"
                        });
                });

            modelBuilder.Entity("Dogtoralia.Shared.Models.Speciality", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Specialities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Medicina General"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Dermatología"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Ortopedia"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Cardiología"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Oncología"
                        });
                });

            modelBuilder.Entity("Dogtoralia.Shared.Models.Veterinarian", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClinicId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LicenseNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("YearsOfExperience")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ClinicId");

                    b.HasIndex("LicenseNumber")
                        .IsUnique();

                    b.ToTable("Veterinarians");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ClinicId = 1,
                            Email = "c.mendoza@sanangelvет.mx",
                            FirstName = "Carlos",
                            LastName = "Mendoza Ruiz",
                            LicenseNumber = "MV-100001",
                            Phone = "+52-55-5550-1101",
                            YearsOfExperience = 10
                        },
                        new
                        {
                            Id = 2,
                            ClinicId = 1,
                            Email = "l.garcia@sanangelvет.mx",
                            FirstName = "Laura",
                            LastName = "García Pérez",
                            LicenseNumber = "MV-100002",
                            Phone = "+52-55-5550-1102",
                            YearsOfExperience = 7
                        },
                        new
                        {
                            Id = 3,
                            ClinicId = 2,
                            Email = "m.torres@dermapetpolanco.mx",
                            FirstName = "Miguel",
                            LastName = "Torres Sánchez",
                            LicenseNumber = "MV-100003",
                            Phone = "+52-55-5550-2101",
                            YearsOfExperience = 12
                        },
                        new
                        {
                            Id = 4,
                            ClinicId = 2,
                            Email = "a.lopez@dermapetpolanco.mx",
                            FirstName = "Ana",
                            LastName = "López Hernández",
                            LicenseNumber = "MV-100004",
                            Phone = "+52-55-5550-2102",
                            YearsOfExperience = 5
                        },
                        new
                        {
                            Id = 5,
                            ClinicId = 3,
                            Email = "r.castillo@gdl.mx",
                            FirstName = "Roberto",
                            LastName = "Castillo Vega",
                            LicenseNumber = "MV-100005",
                            Phone = "+52-33-3333-3101",
                            YearsOfExperience = 15
                        },
                        new
                        {
                            Id = 6,
                            ClinicId = 3,
                            Email = "s.ramirez@gdl.mx",
                            FirstName = "Sofia",
                            LastName = "Ramírez Díaz",
                            LicenseNumber = "MV-100006",
                            Phone = "+52-33-3333-3102",
                            YearsOfExperience = 8
                        },
                        new
                        {
                            Id = 7,
                            ClinicId = 4,
                            Email = "d.morales@mty.mx",
                            FirstName = "Diego",
                            LastName = "Morales Cruz",
                            LicenseNumber = "MV-100007",
                            Phone = "+52-81-8181-4101",
                            YearsOfExperience = 20
                        },
                        new
                        {
                            Id = 8,
                            ClinicId = 4,
                            Email = "v.jimenez@mty.mx",
                            FirstName = "Valeria",
                            LastName = "Jiménez Flores",
                            LicenseNumber = "MV-100008",
                            Phone = "+52-81-8181-4102",
                            YearsOfExperience = 6
                        },
                        new
                        {
                            Id = 9,
                            ClinicId = 5,
                            Email = "h.reyes@puebla.mx",
                            FirstName = "Héctor",
                            LastName = "Reyes Martínez",
                            LicenseNumber = "MV-100009",
                            Phone = "+52-22-2222-5101",
                            YearsOfExperience = 18
                        },
                        new
                        {
                            Id = 10,
                            ClinicId = 6,
                            Email = "c.navarro@coyoacanvet.mx",
                            FirstName = "Carmen",
                            LastName = "Navarro Ortiz",
                            LicenseNumber = "MV-100010",
                            Phone = "+52-55-5550-6101",
                            YearsOfExperience = 9
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Dogtoralia.Shared.Models.Appointment", b =>
                {
                    b.HasOne("Dogtoralia.Shared.Models.Clinic", "Clinic")
                        .WithMany("Appointments")
                        .HasForeignKey("ClinicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Dogtoralia.Shared.Models.Pet", "Pet")
                        .WithMany("Appointments")
                        .HasForeignKey("PetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Dogtoralia.Shared.Models.Veterinarian", "Veterinarian")
                        .WithMany("Appointments")
                        .HasForeignKey("VeterinarianId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Clinic");

                    b.Navigation("Pet");

                    b.Navigation("Veterinarian");
                });

            modelBuilder.Entity("Dogtoralia.Shared.Models.Clinic", b =>
                {
                    b.HasOne("Dogtoralia.Shared.Models.Speciality", "Speciality")
                        .WithMany("Clinics")
                        .HasForeignKey("SpecialityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Speciality");
                });

            modelBuilder.Entity("Dogtoralia.Shared.Models.Pet", b =>
                {
                    b.HasOne("Dogtoralia.Shared.Models.PetOwner", "PetOwner")
                        .WithMany("Pets")
                        .HasForeignKey("PetOwnerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PetOwner");
                });

            modelBuilder.Entity("Dogtoralia.Shared.Models.Veterinarian", b =>
                {
                    b.HasOne("Dogtoralia.Shared.Models.Clinic", "Clinic")
                        .WithMany("Veterinarians")
                        .HasForeignKey("ClinicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Clinic");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Dogtoralia.Shared.Models.Clinic", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("Veterinarians");
                });

            modelBuilder.Entity("Dogtoralia.Shared.Models.Pet", b =>
                {
                    b.Navigation("Appointments");
                });

            modelBuilder.Entity("Dogtoralia.Shared.Models.PetOwner", b =>
                {
                    b.Navigation("Pets");
                });

            modelBuilder.Entity("Dogtoralia.Shared.Models.Speciality", b =>
                {
                    b.Navigation("Clinics");
                });

            modelBuilder.Entity("Dogtoralia.Shared.Models.Veterinarian", b =>
                {
                    b.Navigation("Appointments");
                });
#pragma warning restore 612, 618
        }
    }
}
